"""CLI: build vision/synth_intrinsics.yaml from camera parameters (spec 6).

Two ways to specify the camera (mirrors common.intrinsics.CameraIntrinsics):
  * field of view:      --hfov DEG           (square pixels unless --vfov given)
  * focal + aperture:   --focal-mm F --aperture-mm A   (the USD/Isaac Sim way)

Writes 길남's EXACT synth_intrinsics.yaml schema (CONVENTIONS.md / the real file
at overall_gilnam/vision/synth_intrinsics.yaml):

    {width, height, fx, fy, cx, cy, distortion}

The distortion field is named `distortion` (a list; an empty list `[]` means the
distortion-free sim camera) -- NOT `distortion_model`/`distortion_coeffs`, and
there is NO hfov/vfov. CameraIntrinsics.to_yaml_dict() carries extra convenience
fields, so this script writes the REDUCED 길남 dict explicitly (common/ unchanged).
길남's loader reads fx/fy/cx/cy directly (vision/synth_scene.py:load_intrinsics),
so the field names must match exactly.

Examples
--------
  python3 scripts/gen_intrinsics.py --width 1280 --height 720 --hfov 90
  python3 scripts/gen_intrinsics.py --width 1280 --height 720 \
          --focal-mm 18.147 --aperture-mm 36.0
"""
from __future__ import annotations

import argparse
import os
import sys

import yaml

# --- shared 'common' package regardless of cwd -------------------------------
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)
from common import CameraIntrinsics  # noqa: E402

_DEFAULT_OUT = os.path.join(_ROOT, "vision", "synth_intrinsics.yaml")

_HEADER = """\
# vision/synth_intrinsics.yaml — spec-6 synthetic camera intrinsics
#
# Generated by scripts/gen_intrinsics.py. Fields are 길남's EXACT schema
# {{width, height, fx, fy, cx, cy, distortion}} (distortion: [] == no distortion).
# TODO(길남): replace with the REAL Isaac Sim camera numbers; keep field names.
# NOTE: the same fx/fy/cx/cy must also land in the calib camchain (via
# calib/fill_from_intrinsics.py) and in 태민's node constants (FX/FY/CX/CY).
# Regenerate with the exact command:
#   {cmd}
"""


def gilnam_intrinsics_dict(intr: CameraIntrinsics) -> dict:
    """길남's EXACT synth_intrinsics.yaml schema: {width,height,fx,fy,cx,cy,distortion}.

    The distortion field is a list; `[]` means the distortion-free sim camera.
    We build this REDUCED dict explicitly (NOT CameraIntrinsics.to_yaml_dict(),
    which adds distortion_model/distortion_coeffs/hfov_deg/vfov_deg) so the output
    matches 길남's field set exactly without changing common/.
    """
    dist = [float(c) for c in intr.distortion]
    return {
        "width": int(intr.width),
        "height": int(intr.height),
        "fx": float(intr.fx),
        "fy": float(intr.fy),
        "cx": float(intr.cx),
        "cy": float(intr.cy),
        # [] == no distortion (sim-camera convention); emit coeffs only if
        # distortion was deliberately rendered (any nonzero).
        "distortion": dist if any(dist) else [],
    }


def build_intrinsics(args: argparse.Namespace) -> CameraIntrinsics:
    """Turn parsed CLI args into a CameraIntrinsics (validates the FOV/focal choice)."""
    use_fov = args.hfov is not None
    use_focal = args.focal_mm is not None or args.aperture_mm is not None
    if use_fov == use_focal:
        raise SystemExit(
            "specify EITHER --hfov OR (--focal-mm AND --aperture-mm), not both/neither."
        )

    if use_fov:
        return CameraIntrinsics.from_fov(
            args.width, args.height, args.hfov, vfov_deg=args.vfov, cx=args.cx, cy=args.cy
        )

    if args.focal_mm is None or args.aperture_mm is None:
        raise SystemExit("--focal-mm and --aperture-mm must be given together.")
    intr = CameraIntrinsics.from_focal_aperture(
        args.width,
        args.height,
        args.focal_mm,
        args.aperture_mm,
        vertical_aperture_mm=args.vaperture_mm,
    )
    # from_focal_aperture centres cx/cy; honour explicit overrides if given.
    if args.cx is not None:
        intr.cx = args.cx
    if args.cy is not None:
        intr.cy = args.cy
    return intr


def write_yaml(intr: CameraIntrinsics, out_path: str, cmd: str) -> None:
    body = yaml.safe_dump(gilnam_intrinsics_dict(intr), sort_keys=False, default_flow_style=False)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(_HEADER.format(cmd=cmd))
        f.write(body)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--width", type=int, required=True, help="image width (px).")
    p.add_argument("--height", type=int, required=True, help="image height (px).")
    p.add_argument("--hfov", type=float, help="horizontal FOV (deg).")
    p.add_argument("--vfov", type=float, help="optional vertical FOV (deg); else square pixels.")
    p.add_argument("--focal-mm", type=float, help="focal length (mm) [USD-style].")
    p.add_argument("--aperture-mm", type=float, help="horizontal aperture (mm) [USD-style].")
    p.add_argument("--vaperture-mm", type=float, help="optional vertical aperture (mm).")
    p.add_argument("--cx", type=float, help="principal point x (px); default W/2.")
    p.add_argument("--cy", type=float, help="principal point y (px); default H/2.")
    p.add_argument("--out", default=_DEFAULT_OUT, help="output yaml (default vision/synth_intrinsics.yaml).")
    return p


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    intr = build_intrinsics(args)
    cmd = "python3 " + " ".join(["scripts/gen_intrinsics.py", *(sys.argv[1:] if argv is None else argv)])
    write_yaml(intr, args.out, cmd)
    d = gilnam_intrinsics_dict(intr)
    print(f"wrote {args.out}")
    print(f"  {d['width']}x{d['height']}  fx={d['fx']:.4f} fy={d['fy']:.4f} "
          f"cx={d['cx']:.1f} cy={d['cy']:.1f}  distortion={d['distortion']}"
          f"  (hfov={intr.hfov_deg:.4f} vfov={intr.vfov_deg:.4f}, derived/not written)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
