function qc_mhe_defaults()
%QC_MHE_DEFAULTS  MHE 설정 기본값을 base 워크스페이스에 채운다 (이미 있으면 안 덮는다).
%
%   값의 근거는 전부 2026-08-29 파이썬 실측이다 (`mhe_estimator.py`, 테스트 19개).
%   임의로 바꾸면 그 실측이 무효가 되므로, 바꿀 때는 재측정할 것.

D = { ...
  'mhe_dt',          0.001,   '제어 주기 [s]'; ...
  'mhe_horizon_s',   0.25,    '창 길이 [s] — ★ 지연이 아니라 관측 가능성이 정한다'; ...
  'mhe_meas_std',    0.01,    '측정 1 표본 위치 오차 [m] (VIO)'; ...
  'mhe_bias_rw',     3.0,     '창 하나 동안 바이어스 허용 변화 [m/s^2] = 사전의 느슨함'; ...
  'mhe_prior_p_std', 1.0,     '위치 사전 [m] — 느슨하게, 측정이 결정하게'; ...
  'mhe_prior_v_std', 1.0,     '속도 사전 [m/s]'; ...
  'mhe_tol_m',       0.005,   '외삽 허용 오차 [m] — ★ N 이 여기서 나온다'; ...
  'mhe_age_trust',   0.7,     '보고된 나이의 이 비율만 되감는다. >1 금지'; ...
  'mhe_dropout_s',   0.25,    '측정이 끊기면 추측항법 중단 [s]'; ...
  'mhe_innov_max',   0.50,    '혁신이 이 이상이면 센서로 스냅 [m]'; ...
  'mhe_v_max',       3.0,     '이탈 한계 계산용 최대 속도 [m/s]'; ...
  'mhe_dev_margin',  0.05,    '이탈 한계 여유 [m]'; ...
  'mhe_n_max',       200,     'N 상한 — 측정보다 드물게 돌 이유가 없다'; ...
  'mhe_g',           9.80665, '중력 [m/s^2]. a_x=+g*pitch, a_y=-g*roll (08-29 부호 실측)'};

for k = 1:size(D,1)
    n = D{k,1};
    % 중첩 따옴표를 피해 char(39) 로 조립한다 — 읽기는 나빠도 이식·생성이 안전하다.
    Q = char(39);
    if ~evalin('base', ['exist(' Q n Q ',' Q 'var' Q ')'])
        assignin('base', n, D{k,2});
    end
end
end
